# ruff: noqa: E501

"""Send a formal email report for one GitHub Actions data publication run.

The script intentionally uses only Python's standard library.  It reads the
human-readable report generated by ``run_pipeline()``, compares publication
files with the pre-run hashes saved by the workflow, and sends both HTML and
plain-text email through any SMTP provider.
"""

from __future__ import annotations

import hashlib
import html
import os
import re
import smtplib
import sqlite3
import sys
from dataclasses import dataclass, field
from email.message import EmailMessage
from pathlib import Path

INDICATOR_RE = re.compile(
    r"^\s*-\s+(?P<code>.+?): requested (?P<requested>\d+); "
    r"extracted (?P<extracted>\d+); history DB written (?P<history>\d+); "
    r"snapshot DB contains (?P<snapshot>\d+)"
)
DATASET_RE = re.compile(r"^\[(?P<status>[A-Z]+)\]\s+(?P<dataset>.+)$")


@dataclass
class DatasetSummary:
    name: str
    status: str
    indicators: int = 0
    requested: int = 0
    extracted: int = 0
    history: int = 0
    snapshot: int = 0
    issues: list[str] = field(default_factory=list)


@dataclass
class RunSummary:
    status: str = "unknown"
    run_id: str = "unknown"
    started: str = "unknown"
    completed: str = "unknown"
    lookback: str = "unknown"
    datasets: list[DatasetSummary] = field(default_factory=list)
    derived_materialised: str = "0"
    derived_skipped: str = "0"
    sources: dict[str, list[str]] = field(default_factory=dict)


@dataclass
class Publication:
    label: str
    local_path: Path
    destination: str
    before_hash: str | None = None
    after_hash: str | None = None
    state: str = "not available"
    meaningful_change: bool = False


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def _read_report(report_dir: Path) -> tuple[RunSummary, Path | None]:
    reports = sorted(report_dir.glob("run_report_*.txt"), key=lambda path: path.stat().st_mtime)
    report_path = reports[-1] if reports else None
    summary = RunSummary()
    if report_path is None:
        return summary, None

    current: DatasetSummary | None = None
    for raw_line in report_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("Run:"):
            summary.run_id = line.partition(":")[2].strip()
        elif line.startswith("Status:"):
            summary.status = line.partition(":")[2].strip()
        elif line.startswith("Started:"):
            summary.started = line.partition(":")[2].strip()
        elif line.startswith("Collection completed:"):
            summary.completed = line.partition(":")[2].strip()
        elif line.startswith("LOOKBACK_PERIOD requested:"):
            summary.lookback = line.partition(":")[2].strip()
        elif line.startswith("DERIVED INDICATORS"):
            current = None
        elif line.startswith("Materialised:"):
            summary.derived_materialised = line.partition(":")[2].strip()
        elif line.startswith("Skipped:"):
            summary.derived_skipped = line.partition(":")[2].strip()

        dataset_match = DATASET_RE.match(line)
        if dataset_match:
            current = DatasetSummary(
                name=dataset_match.group("dataset"),
                status=dataset_match.group("status"),
            )
            summary.datasets.append(current)
            summary.sources[current.name] = []
            continue

        indicator_match = INDICATOR_RE.match(raw_line)
        if indicator_match and current is not None:
            current.indicators += 1
            current.requested += int(indicator_match.group("requested"))
            current.extracted += int(indicator_match.group("extracted"))
            current.history += int(indicator_match.group("history"))
            current.snapshot += int(indicator_match.group("snapshot"))
        elif line.startswith("Issue:") and current is not None:
            current.issues.append(line.partition(":")[2].strip())
        elif line.startswith("Warning:") and current is not None:
            current.issues.append(line.partition(":")[2].strip())
        elif line.startswith("http") and current is not None:
            summary.sources[current.name].append(line)

    return summary, report_path


def _sha256(path: Path) -> str | None:
    if not path.is_file():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _observation_count(path: Path) -> int | None:
    if not path.is_file():
        return None
    try:
        with sqlite3.connect(path) as connection:
            return int(connection.execute("SELECT COUNT(*) FROM observations").fetchone()[0])
    except sqlite3.Error:
        return None


def _load_publications() -> list[Publication]:
    private_bucket = os.getenv("R2_PRIVATE_BUCKET", "paisometro-private")
    public_bucket = os.getenv("R2_PUBLIC_BUCKET", "paisometro-public")
    snapshot_key = os.getenv("SNAPSHOT_R2_KEY", "backups/<run>/snapshot.db")
    return [
        Publication(
            "History database",
            Path(os.getenv("HISTORY_DB_PATH", "")),
            f"s3://{private_bucket}/history.db",
        ),
        Publication(
            "Snapshot database",
            Path(os.getenv("SNAPSHOT_DB_PATH", "")),
            f"s3://{private_bucket}/{snapshot_key}",
        ),
        Publication(
            "Budget execution JSON",
            Path(os.getenv("BUDGET_HISTORY_PATH", "")),
            f"s3://{public_bucket}/v1/budget_execution_history.json",
        ),
        Publication(
            "Dashboard JSON",
            Path(os.getenv("DASHBOARD_PATH", "")),
            f"s3://{public_bucket}/v1/paisometro-dashboard.json",
        ),
    ]


def _load_publication_states(publications: list[Publication], runtime_dir: Path) -> None:
    baseline_path = runtime_dir / "publication_baseline.json"
    try:
        import json

        baseline_payload = json.loads(baseline_path.read_text(encoding="utf-8"))
        baseline = baseline_payload.get("files", baseline_payload)
        baseline_observations = baseline_payload.get("history_observations")
    except (OSError, ValueError):
        baseline = {}
        baseline_observations = None

    for publication in publications:
        publication.before_hash = baseline.get(publication.label)
        publication.after_hash = _sha256(publication.local_path)
        if publication.after_hash is None:
            publication.state = "not generated"
        elif publication.before_hash is None:
            publication.state = "created or restored"
        elif publication.before_hash != publication.after_hash:
            publication.state = "updated"
        else:
            publication.state = "unchanged"

        # history.db contains ingestion metadata that changes every run.  Its
        # observation count is the meaningful signal for email notifications.
        if publication.label == "History database":
            current_observations = _observation_count(publication.local_path)
            if current_observations is not None and baseline_observations is not None:
                publication.meaningful_change = current_observations != int(baseline_observations)
                if publication.meaningful_change:
                    publication.state = (
                        f"updated ({current_observations - int(baseline_observations):+d} observations)"
                    )
            else:
                publication.meaningful_change = publication.after_hash is not None
        elif publication.label != "Snapshot database":
            publication.meaningful_change = publication.state in {
                "created or restored",
                "updated",
            }


def _job_status() -> str:
    return os.getenv("RUN_CONCLUSION", os.getenv("JOB_STATUS", "success")).lower()


def _should_send(publications: list[Publication]) -> bool:
    if not _env_bool("EMAIL_ONLY_ON_CHANGES", True):
        return True
    return _job_status() != "success" or any(
        publication.meaningful_change for publication in publications
    )


def _status_color(status: str) -> str:
    return {
        "success": "#157347",
        "partial": "#9a6700",
        "failed": "#b42318",
        "failure": "#b42318",
        "cancelled": "#667085",
    }.get(status.lower(), "#475467")


def _dataset_totals(summary: RunSummary) -> tuple[int, int, int, int]:
    return tuple(
        sum(getattr(dataset, attribute) for dataset in summary.datasets)
        for attribute in ("extracted", "history", "snapshot", "indicators")
    )  # type: ignore[return-value]


def _html_report(
    summary: RunSummary,
    publications: list[Publication],
    report_path: Path | None,
) -> str:
    status = html.escape(_job_status().upper())
    status_color = _status_color(_job_status())
    extracted, history, snapshot, _ = _dataset_totals(summary)
    workflow_url = (
        f"{os.getenv('GITHUB_SERVER_URL', 'https://github.com')}/"
        f"{os.getenv('GITHUB_REPOSITORY', '')}/actions/runs/{os.getenv('GITHUB_RUN_ID', '')}"
    )

    dataset_rows = "".join(
        "<tr>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0'>{html.escape(item.name)}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0;color:{_status_color(item.status)};font-weight:700'>{html.escape(item.status)}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0;text-align:right'>{item.indicators}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0;text-align:right'>{item.extracted}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0;text-align:right'>{item.history}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0;text-align:right'>{item.snapshot}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0'>{html.escape('; '.join(item.issues) or '—')}</td>"
        "</tr>"
        for item in summary.datasets
    )
    publication_rows = "".join(
        "<tr>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0'>{html.escape(item.label)}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0'>{html.escape(item.state)}</td>"
        f"<td style='padding:10px;border-bottom:1px solid #eaecf0;font-family:monospace;font-size:12px'>{html.escape(item.destination)}</td>"
        "</tr>"
        for item in publications
    )
    report_link = (
        f"<a href='{html.escape(workflow_url)}' style='color:#175cd3'>Ver ejecución en GitHub Actions</a>"
        if os.getenv("GITHUB_RUN_ID")
        else html.escape(str(report_path or "No disponible"))
    )
    return f"""<!doctype html>
<html lang="es"><body style="margin:0;background:#f5f7fa;color:#1d2939;font-family:Arial,Helvetica,sans-serif">
<div style="max-width:1100px;margin:0 auto;padding:28px 16px">
  <div style="background:#17324d;color:#fff;padding:28px 30px;border-radius:10px 10px 0 0">
    <div style="font-size:12px;letter-spacing:1.2px;text-transform:uppercase;color:#b9d7ee">Paisómetro · Informe automático</div>
    <h1 style="margin:8px 0 4px;font-size:26px">Publicación de datos</h1>
    <div style="font-size:14px;color:#d0e2f0">Ejecución #{html.escape(summary.run_id)}</div>
  </div>
  <div style="background:#fff;padding:24px 30px;border-radius:0 0 10px 10px;box-shadow:0 2px 10px #10182812">
    <div style="display:inline-block;padding:7px 13px;border-radius:20px;background:{status_color}15;color:{status_color};font-weight:700">{status}</div>
    <p style="font-size:15px;line-height:1.5">Este informe resume la ejecución automática de ingestión y la publicación de los ficheros de Paisómetro en Cloudflare R2.</p>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:18px 0"><tr>
      <td style="padding:14px;background:#f2f4f7;border-radius:8px"><div style="font-size:12px;color:#667085">Valores extraídos</div><div style="font-size:23px;font-weight:700">{extracted}</div></td>
      <td width="12"></td>
      <td style="padding:14px;background:#f2f4f7;border-radius:8px"><div style="font-size:12px;color:#667085">Escrituras en history.db</div><div style="font-size:23px;font-weight:700">{history}</div></td>
      <td width="12"></td>
      <td style="padding:14px;background:#f2f4f7;border-radius:8px"><div style="font-size:12px;color:#667085">Valores en snapshot.db</div><div style="font-size:23px;font-weight:700">{snapshot}</div></td>
    </tr></table>
    <h2 style="font-size:18px;margin:28px 0 10px">Resumen de datasets</h2>
    <div style="overflow-x:auto"><table width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #eaecf0;border-radius:8px;border-collapse:separate;border-spacing:0;font-size:13px">
      <tr style="background:#f9fafb"><th align="left" style="padding:10px">Dataset</th><th align="left" style="padding:10px">Estado</th><th align="right" style="padding:10px">Indicadores</th><th align="right" style="padding:10px">Extraídos</th><th align="right" style="padding:10px">History</th><th align="right" style="padding:10px">Snapshot</th><th align="left" style="padding:10px">Incidencias</th></tr>
      {dataset_rows or '<tr><td colspan="7" style="padding:12px">No se pudo localizar el informe de ejecución.</td></tr>'}
    </table></div>
    <h2 style="font-size:18px;margin:28px 0 10px">Ficheros publicados</h2>
    <table width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #eaecf0;border-radius:8px;border-collapse:separate;border-spacing:0;font-size:13px">
      <tr style="background:#f9fafb"><th align="left" style="padding:10px">Fichero</th><th align="left" style="padding:10px">Resultado</th><th align="left" style="padding:10px">Destino</th></tr>
      {publication_rows}
    </table>
    <p style="margin-top:26px;font-size:14px">LOOKBACK_PERIOD: <strong>{html.escape(summary.lookback)}</strong><br>Inicio: {html.escape(summary.started)}<br>Fin de colección: {html.escape(summary.completed)}<br>{report_link}</p>
    <p style="font-size:12px;color:#667085;border-top:1px solid #eaecf0;padding-top:16px">Indicadores derivados materializados: {html.escape(summary.derived_materialised)} · Omitidos: {html.escape(summary.derived_skipped)}</p>
  </div>
</div></body></html>"""


def _text_report(
    summary: RunSummary,
    publications: list[Publication],
    report_path: Path | None,
) -> str:
    extracted, history, snapshot, _ = _dataset_totals(summary)
    lines = [
        "PAISÓMETRO — INFORME AUTOMÁTICO DE PUBLICACIÓN",
        f"Estado: {_job_status().upper()}",
        f"Ejecución: #{summary.run_id}",
        f"LOOKBACK_PERIOD: {summary.lookback}",
        f"Valores extraídos: {extracted}",
        f"Escrituras en history.db: {history}",
        f"Valores en snapshot.db: {snapshot}",
        "",
        "DATASETS",
    ]
    for item in summary.datasets:
        issue = f" | Incidencias: {'; '.join(item.issues)}" if item.issues else ""
        lines.append(
            f"- {item.name}: {item.status}; {item.extracted} extraídos; "
            f"{item.history} history; {item.snapshot} snapshot{issue}"
        )
    lines.extend(("", "FICHEROS PUBLICADOS"))
    for item in publications:
        lines.append(f"- {item.label}: {item.state} -> {item.destination}")
    lines.extend(
        (
            "",
            f"Derivados materializados: {summary.derived_materialised}",
            f"Derivados omitidos: {summary.derived_skipped}",
            f"Informe local: {report_path or 'no disponible'}",
        )
    )
    return "\n".join(lines) + "\n"


def _send_email(
    summary: RunSummary,
    publications: list[Publication],
    report_path: Path | None,
) -> None:
    host = os.getenv("SMTP_HOST", "").strip()
    username = os.getenv("SMTP_USERNAME", "").strip()
    password = os.getenv("SMTP_PASSWORD", "")
    sender = os.getenv("SMTP_FROM", username).strip()
    recipients = [item.strip() for item in os.getenv("SMTP_TO", "").split(",") if item.strip()]
    if not host or not sender or not recipients:
        print("SMTP email not configured; notification skipped.")
        return

    repository = os.getenv("GITHUB_REPOSITORY", "Paisómetro")
    subject_prefix = os.getenv("SMTP_SUBJECT_PREFIX", "Paisómetro")
    subject = f"[{_job_status().upper()}] {subject_prefix} — data publication #{summary.run_id}"
    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = sender
    message["To"] = ", ".join(recipients)
    message["X-Paisometro-Run"] = summary.run_id
    message.set_content(_text_report(summary, publications, report_path))
    message.add_alternative(_html_report(summary, publications, report_path), subtype="html")

    port = int(os.getenv("SMTP_PORT", "465"))
    use_tls = _env_bool("SMTP_USE_TLS", port != 465)
    if port == 465 and not use_tls:
        with smtplib.SMTP_SSL(host, port, timeout=30) as client:
            if username:
                client.login(username, password)
            client.send_message(message)
    else:
        with smtplib.SMTP(host, port, timeout=30) as client:
            client.ehlo()
            if use_tls:
                client.starttls()
                client.ehlo()
            if username:
                client.login(username, password)
            client.send_message(message)
    print(f"Publication email sent to {len(recipients)} recipient(s) for {repository}.")


def main() -> int:
    runtime_dir = Path(os.getenv("RUNTIME_DIR", ".runtime"))
    summary, report_path = _read_report(runtime_dir)
    publications = _load_publications()
    _load_publication_states(publications, runtime_dir)
    if not _should_send(publications):
        print("No publication changes detected; notification skipped.")
        return 0
    try:
        _send_email(summary, publications, report_path)
    except (OSError, smtplib.SMTPException, ValueError) as exc:
        print(f"Could not send publication email: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
